# -*- coding: utf-8 -*-
"""Nhom7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NV-_DATFtk-19bY9xNamDYxXS2FSGE3M
"""


import polars as pl

df = pl.read_parquet("items.parquet")
df_trans = pl.read_parquet("transactions-2025-12.parquet")
print(df.columns)

import polars as pl

item_df = pl.read_parquet(r"items.parquet")

result = item_df.with_columns([
    # step: 1-5 -> int
    pl.when(
        pl.col("description").str.contains("(?i)cho mẹ bầu")
        & pl.col("description").str.extract(r"step\s*([1-5])", 1).is_null()
    )
    .then(0)
    .otherwise(
        pl.col("description")
        .str.extract(r"step\s*([1-5])", 1)
        .cast(pl.Int8)
    )
    .alias("step"),

    # size -> map thành số
    pl.col("description")
    .str.extract(r"\b(Newborn|S|M|L|XL|XXL)\b", 1)
    .replace({
        "Newborn": 0,
        "S": 1,
        "M": 2,
        "L": 3,
        "XL": 4,
        "XXL": 5
    })
    .cast(pl.Int8)
    .alias("size"),

    # piece -> số
    pl.col("description")
    .str.extract(r"(\d+)\s*miếng", 1)
    .cast(pl.Int16)
    .alias("piece"),
]).select([
    "item_id",
    "category_l1",
    "category_l2",
    "category_l3",
    "category",
    "step",
    "size",
    "piece",
    "description"
])

print(result['size'].unique())
print(result['step'].unique())
print(result['piece'].unique())

print(result)

import polars as pl
from collections import defaultdict

def build_item_sessions(df_trans):
    # tạo session key
    df = df_trans.with_columns(
        (pl.col("customer_id").cast(str) + "_" + pl.col("updated_date").cast(str)).alias("session")
    )

    item_sessions = defaultdict(set)

    for row in df.select(["item_id", "session"]).iter_rows():
        item_sessions[row[0]].add(row[1])

    return item_sessions
item_sessions = build_item_sessions(df_trans)

import math

def get_pair_co_buy_score_fast(item_x, item_a):
    sessions_x = item_sessions.get(item_x, set())
    sessions_a = item_sessions.get(item_a, set())

    return len(sessions_x & sessions_a)

def compute_cat_score(itemX, itemA):
    """
    itemX, itemA: dict chứa các field:
        - category
        - category_l3
        - category_l2
        - category_l1
    """

    # Ưu tiên match từ level chi tiết nhất → tổng quát nhất
    if itemX.get("category") == itemA.get("category"):
        return 1.0
    elif itemX.get("category_l3") == itemA.get("category_l3"):
        return 0.5
    elif itemX.get("category_l2") == itemA.get("category_l2"):
        return 0.25
    elif itemX.get("category_l1") == itemA.get("category_l1"):
        return 0.125
    else:
        return 0.0

def compute_size_score(itemX, itemA, W1=1.5, W2=0.5):
    """
    itemX, itemA: dict chứa key 'size'
    """

    size_X = itemX.get("size")
    size_A = itemA.get("size")

    # handle missing value
    if size_X is None or size_A is None:
        return 1

    diff_XA = max(0, size_X - size_A)
    diff_AX = max(0, size_A - size_X)

    score = math.exp(-W1 * diff_XA - W2 * diff_AX)

    return score

def compute_step_score(itemX, itemA, W1=1.5, W2=0.5):
    """
    itemX, itemA: dict chứa key 'step'
    """

    step_X = itemX.get("step")
    step_A = itemA.get("step")

    # handle missing
    if step_X is None or step_A is None:
        return 1

    try:
        step_X = float(step_X)
        step_A = float(step_A)
    except:
        return 1

    diff_XA = max(0.0, step_X - step_A)
    diff_AX = max(0.0, step_A - step_X)

    return math.exp(-W1 * diff_XA - W2 * diff_AX)


def compute_piece_score(itemX, itemA, W1=1.5, W2=0.5):
    """
    itemX, itemA: dict chứa key 'piece'
    """

    piece_X = itemX.get("piece")
    piece_A = itemA.get("piece")

    # handle missing
    if piece_X is None or piece_A is None:
        return 0.0

    try:
        piece_X = float(piece_X)
        piece_A = float(piece_A)
    except:
        return 0.0

    diff_XA = max(0.0, piece_X - piece_A)
    diff_AX = max(0.0, piece_A - piece_X)

    return math.exp(-W1 * diff_XA - W2 * diff_AX)

def compute_score(itemX, itemA):
    """
    item_X, item_A: dict chứa thông tin item
        {
            "id": ...,
            "category": ...,
            "price": ...
        }
    """

    # 1. co-buy score
    co_buy = get_pair_co_buy_score_fast(itemX['item_id'], itemA['item_id'])

    # 2. category score
    cat_score = compute_cat_score(itemX, itemA)

    # 3. price score
    size_score = compute_size_score(itemX, itemA)

    # 4. step score
    step_score = compute_step_score(itemX, itemA)

    # 5. piece score
    piece_score = compute_piece_score(itemX, itemA)

    # final score
    final_score = co_buy * cat_score * size_score * step_score

    return final_score

def recommend_items(idX, df):
    # lấy đúng 1 row của itemX
    rowX = df.filter(df["item_id"] == idX)

    if rowX.height == 0:
        raise ValueError("itemX không tồn tại")

    itemX = rowX.to_dicts()[0]  # convert thành dict

    results = []
    i = 0
    for row in df.iter_rows(named=True):
        # bỏ chính nó
        i += 1
        # print(f"process data {i}")
        if row["item_id"] == idX:
            continue

        itemA = dict(row)

        score = compute_score(itemX, itemA)

        results.append({
            "item_id": itemA["item_id"],
            "score": score,
            "category" : itemA["category"],
            "description": itemA["description"]
        })

    # sort giảm dần
    results.sort(key=lambda x: x["score"], reverse=True)

    return results

rec = recommend_items(3389000000238, result)
print(rec)